
# MANDATORY SITE SETTINGS
# =======================

languages: ["fr"] #, "en"] # de
default_lang: "fr"
exclude_from_localization: ["js", "img", "css"]
parallel_localization: false

sass:
  sass_dir: css
  style: compressed
  exclude: []

livereload: false
baseurl: ""

exclude: 
  - bin
  - README.md
  - ".*.yml"
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - vendor

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-polyglot
  - jekyll-seo-tag

url: "https://powa-accompagnement.org"

# https://artofhostingparis.org
title: POWA Accompagnement
email: team@powa-accompagnement.org

baseline_i18n:
  fr: "POWA Accompagnement"
  #  en: "Ethical outsourcing in Nepal"

description_i18n:
  fr: "Préparer le futur du travail"
  # en: "Our engagement: offering you top-quality technical services to carry out your website and mobile application projects"

# JEKYLL PLUGINS
# ==============

# Jekyll SEO plugin
lang: fr_FR
# twitter:
#     username: boldcode_io

logo: /img/logos/logo-DT-color-blackbg.256p.png
image: 
    path: /img/logos/logo-DT-color-blackbg.256p.png

# JEKYLL TEMPLATE
# ===============

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#   - title: twitter
#     url: https://twitter.com/boldcode_io 
#     username: "@boldcode_io"
#   - title: facebook
#     url: https://www.facebook.com/boldcode/
#     username: "/boldcode"

# Postal address (add as many lines as necessary)
address:
  - line: xxx

# Build settings
markdown: kramdown
permalink: pretty
# permalink: contact

